---
sudo: required
dist: trusty

language: php
php: "7.0"

services:
  - docker

env:
  global:
  - secure: QCN/3wjqP+Dr0o3dU5TE+gmJgpziglMfqYnxuWnwO4mercNhRAtNatH11coOt9hA+y7tcSCnR2+CPx0PfoIy3aITW1OY7WzD7DfgfAS7WgeRPdGNWmpKvy5wn5OjDZoAaIA5xaTzDwUATqNiYJhzhM5eFzpemPOOimWpzfGNxVuj2uWeb+ILf4JRC+L3xiqAtBH7NDvyJgsJ55kFEnbAB8vBERBhZu736Y36Cr6l02IF6F/1ljS1vb56t4iFF/WekffBqXptjnn9bKYK+QYPAfPRnMgKdiJ9MHB23FenlTv2v4fOMbNyCDpbKvsbqMeNbvlCrWKnGGARGP1ch89RqU0jTZFkloSKQvcVnWpy1el2S8hE8wKnxGqwD+i5AGZyxenbv8d+p27ienQtNQk/ukZdr70GlscEtLwUF9d/uh8Hj0gph4NPEjuS6c5x/JDYMEEwiTf2B4k/2tdG2W0prBgkY3LrTAuTUL2109mFpmOs/RVsMglLj9SsSbFBYMmOLqG+oaiJJNq6tD0/FcZhlpblrxKyrQQ3NmUdnVbzRjp8q1p9yn7uoc8QJrRvdZStnZwQ5V6EHVXgvbzg8oS6C/EQ3DUFXF/5wjhysKl6wKk1mGqyYKw5cB8LemSX0zKVN8RPm7IOgh5kpcAzSc/ISfRp8IfvW7nv4eGBf/43Upc=
  - ENCRYPTION_LABEL: "9bbaa7f542ce"
  - COMMIT_AUTHOR_EMAIL: "christian.wiedemann@key-tec.de"

branches:
  only:
    - master
    - develop

before_install:
  - ./before_install.sh

install:
  - curl -fsSL https://raw.githubusercontent.com/andock-ci/pipeline/master/install-pipeline | sh

script:
  # Check the role/playbook's syntax.
  - acp connect "dev.key-tec.de"
  - acp version
  - acp build
  - acp fin init
  - acp fin update
  - acp fin test
