# Basic LAMP stack
version: "2.1"
services:
  # Web
  web:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: web
    depends_on:
      - cli
  # DB
  db:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: db
  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
  # andock-ci pipeline
  acp:
    hostname: acp
    image: andockci/acp:dev-latest
    volumes:
      - project_root:/var/www:rw,nocopy  # Project root volume

