#!/bin/bash
DOCROOT='docroot'
DOCROOT_PATH=${PROJECT_ROOT}/${DOCROOT}
echo ${PROJECT_ROOT}
# Set to the appropriate site directory

PROJECT='keytec';
ENVS=("dev" "test" "prod" "integration" "backup")

set -e
promptyn () {
    while true; do
        read -p "$1 " yn
        case $yn in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}
#fin exec "cp /var/www/.docksal/drupal/sites.php /var/www/docroot/sites/sites.php"
for ((i=0; i < ${#ENVS}; i++))
do


      SITEDIR_PATH="${DOCROOT_PATH}/sites/${PROJECT}-${ENVS[$i]}"
      REMOTE_SITE=${PROJECT}.${ENVS[$i]}
      if [ "$REMOTE_SITE" = "backup" ]; then
        REMOTE_SITE="prod"
      fi
      if [ "$REMOTE_SITE" = "integration" ]; then
        REMOTE_SITE="prod"
      fi
      if promptyn "Import drush alias @${REMOTE_SITE} in your ${ENVS[$i]} folder?"; then
      sudo mkdir -p ${SITEDIR_PATH}
      sudo cp -R ${PROJECT_ROOT}/.docksal/drupal/files $SITEDIR_PATH
      sudo chmod -R 777 ${SITEDIR_PATH}/files

      sudo cp ${PROJECT_ROOT}/.docksal/drupal/settings.php ${SITEDIR_PATH}/settings.php

      sudo sed -i "s/%%PROJECT%%/${PROJECT}/g" ${SITEDIR_PATH}/settings.php
      sudo sed -i "s/%%ENV%%/${ENVS[i]}/g" ${SITEDIR_PATH}/settings.php


      sudo cp ${PROJECT_ROOT}/.docksal/drupal/services.yml ${SITEDIR_PATH}/services.yml

      cd ${SITEDIR_PATH}

      fin drush sql-create -y

      fin drush sql-sync @${REMOTE_SITE} @self -y

      if promptyn "@${ENVS[$i]}: Apply updates and cim?"; then
        fin drush cr
        fin drush updb -y
        fin drush cim -y
      fi
      if promptyn "Rsync files from drush alias @${REMOTE_SITE} in your ${SITEDIR_PATH}/files folder?"; then
        fin drush -y rsync @${REMOTE_SITE}:sites/default/files @self:sites/${PROJECT}-${ENVS[$i]}
      fi
  fi
done

exit 1;